"""Add BookShelf and BookInShelf models

Revision ID: 051f91187986
Revises: 8af5accd1a59
Create Date: 2026-02-09 14:30:06.340361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051f91187986'
down_revision: Union[str, Sequence[str], None] = '8af5accd1a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookshelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_bookshelf_name')
    )
    op.create_table('books_in_shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_olid', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bookshelf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['bookshelf.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookshelf_id', 'work_olid', name='uq_bookshelf_openlibrary_book')
    )
    op.create_index(op.f('ix_books_in_shelf_work_olid'), 'books_in_shelf', ['work_olid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_in_shelf_work_olid'), table_name='books_in_shelf')
    op.drop_table('books_in_shelf')
    op.drop_table('bookshelf')
    # ### end Alembic commands ###
