"""add UserBook model

Revision ID: 34b1b3760417
Revises: 051f91187986
Create Date: 2026-02-11 18:21:25.938145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b1b3760417'
down_revision: Union[str, Sequence[str], None] = '051f91187986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_olid', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'READING', 'COMPLETED', 'DROPPED', name='reading_status_enum', native_enum=False), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='check_progress_range'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='check_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_olid', name='uq_user_work')
    )
    op.create_index(op.f('ix_user_books_user_id'), 'user_books', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_books_work_olid'), 'user_books', ['work_olid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_books_work_olid'), table_name='user_books')
    op.drop_index(op.f('ix_user_books_user_id'), table_name='user_books')
    op.drop_table('user_books')
    # ### end Alembic commands ###
