"""Add user model

Revision ID: 8142d1370b68
Revises: 11031cbb97de
Create Date: 2026-02-05 18:11:55.869814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8142d1370b68'
down_revision: Union[str, Sequence[str], None] = '11031cbb97de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_favorite_work'), 'favorites', type_='unique')
    op.create_unique_constraint('uq_favorite_work_user', 'favorites', ['work_olid', 'user_id'])
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint('uq_favorite_work_user', 'favorites', type_='unique')
    op.create_unique_constraint(op.f('uq_favorite_work'), 'favorites', ['work_olid'], postgresql_nulls_not_distinct=False)
    op.drop_column('favorites', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
