"""Update Book and Favorite models

Revision ID: 875ea641f2fd
Revises: d228769b6281
Create Date: 2026-02-11 18:57:19.456184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875ea641f2fd'
down_revision: Union[str, Sequence[str], None] = 'd228769b6281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorites', 'books', ['work_olid'], ['work_olid'])
    op.drop_column('favorites', 'year')
    op.drop_column('favorites', 'title')
    op.drop_column('favorites', 'authors')
    op.drop_column('favorites', 'cover_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('cover_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('authors', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    # ### end Alembic commands ###
